[package]
name = "print_warnings"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"

[features]
nightly = ["const_format/assert", "const_format/const_generics"]

[dependencies]
const_format = {path = "../const_format/"}